[package]
name = "tmsu-nautilus"
version = "0.4.0"
authors = ["Andrew Shu <talklittle@gmail.com>"]

[lib]
name = "tmsu_nautilus"
crate-type = ["dylib"]

[dependencies]
gdk = "0.7.0"
glib = "0.4.0"
glib-sys = "0.5.0"
gobject-sys = "0.5.0"
libc = "0.2"
nautilus-extension = "0.3.0"
url = "1.2.0"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_18"]

[dependencies.gtk-sys]
version = "0.5.0"
features = ["v3_18"]
