name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnautilus-extension-dev libgtk-3-0
      - name: Build release
        run: make clean compile dist
      - name: Create .deb
        run: |
          cargo install cargo-deb
          cargo deb --no-build
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            tmsu-nautilus-*/libtmsu-nautilus.so
            target/debian/tmsu-nautilus*.deb
